feat(type): new v11 specs
carbon-design-system/design-language-website pull request #1091
Opened 2022-03-28 21:22 UTC by sstrubberg

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2022-03-29 18:55 UTC, aagonzales requested changes

2022-03-29 18:55 UTC, aagonzales commented on src/pages/typography/type-specs-ui.mdx
> +## Utility styles
In the context of these pages I think these headers could be H3s
```suggestion
### Utility styles
```

2022-03-29 18:55 UTC, aagonzales commented on src/pages/typography/type-specs-ui.mdx
> +## Body styles
```suggestion
### Body styles
```

2022-03-29 18:55 UTC, aagonzales commented on src/pages/typography/type-specs-ui.mdx
> +## Fixed heading styles
```suggestion
### Fixed heading styles
```

2022-03-29 18:55 UTC, aagonzales commented on src/pages/typography/type-specs-ui.mdx
> +## Fluid heading styles
```suggestion
### Fluid heading styles
```

2022-03-29 18:55 UTC, aagonzales commented on src/pages/typography/type-specs-ui.mdx
> +[Type usage](/guidelines/typography/type-usage).
Outdated link, its actually a [v11 link](https://v11.carbondesignsystem.com/guidelines/typography/styling-strategies) so it wont work yet.
```suggestion
[Type usage](https://carbondesignsystem.com/guidelines/typography/styling-strategiese).
```

2022-03-29 18:55 UTC, aagonzales commented on src/pages/typography/type-specs-ui.mdx
> +[Type usage](/guidelines/typography/type-usage#expressive-use-cases/).
Broken link, current [V11 link](https://v11.carbondesignsystem.com/guidelines/typography/styling-strategies#expressive-use-cases)

```suggestion
[Type usage](https://carbondesignsystem.com/guidelines/typography/styling-strategies#expressive-use-cases).
```

2022-03-29 20:44 UTC, aledavila approved these changes
lgtm

2022-03-30 03:07 UTC, jnm2377 approved these changes

2022-03-30 03:08 UTC, merged