IDL Pictograms/Design - action icons
carbon-design-system/design-language-website pull request #724
Opened 2020-09-10 11:37 UTC by DianaStanciulescu

Edit action icons from launch to arrow right for resource cards linking to pages on the same site.

2020-09-10 17:57 UTC, jnm2377 approved these changes

2020-09-10 21:21 UTC, vpicone requested changes

2020-09-10 21:21 UTC, vpicone commented on src/pages/iconography/pictograms/design.mdx
> +      href="/color/#gradients"
You don't want to include a slash before the `#` when linking to a particular spot
```suggestion
      href="/color#gradients"
```

2020-09-10 21:22 UTC, vpicone commented on src/pages/iconography/pictograms/usage.mdx
> +      href="https://www.ibm.com/design/language/2x-grid#the-mini-unit"
This one is correct

2020-09-10 21:22 UTC, vpicone requested changes
Minor href change

2020-09-11 09:10 UTC, DianaStanciulescu commented
thanks @vpicone! I did not check the rest of the resource, just changed the icon, great observation!

2020-09-11 11:48 UTC, vpicone approved these changes

2020-09-11 11:48 UTC, merged